---
name: Reference gen
# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  # push:
  #   branches-ignore:
  #     - main
  workflow_dispatch:

jobs:
  ReferenceGen:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # default 6 hour
    env:
      TZ: Asia/Tokyo
      BUILD_FFMPEG_VERSION: null
      COMMIT_SHORT_SHA: null
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.1.4

      - name: Set short git commit SHA
        run: |+
          set -eux

          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Installing FFmpeg
        run: |+
          set -eux

          sudo apt-get update
          sudo apt-get -y install aria2

      - name: Installing dependencies
        run: |+
          set -eux

          sudo apt-get update
          sudo apt-get -y install aria2

      - name: Download Big Buck Bunny
        run: |+
          set -eux

          mkdir -p src
          curl -sfSL https://media.xiph.org/BBB/BBB-1080-png/MD5SUMS.txt | \
          awk '{print $2}' | \
          sed -e 's@^@https://media.xiph.org/BBB/BBB-1080-png/@g' > pnglist.txt

          aria2c --dir=./src \
            --input-file=pnglist.txt \
            --max-concurrent-downloads=4 \
            --connect-timeout=5 \
            --max-connection-per-server=16 \
            --split=3 \
            --min-split-size=5M \
            --human-readable=true \
            --download-result=full \
            --file-allocation=none

      - name: Installing FFmpeg
        run: |+
          set -eux

          curl -fSL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \
            -o ffmpeg-release-amd64-static.tar.xz
          ## FFmpeg 7.0
          echo "f8997c40659a38818d593f720c5ff188  ffmpeg-release-amd64-static.tar.xz" | md5sum --check -

          mkdir -p bin
          tar -xvf ffmpeg-release-amd64-static.tar.xz -C bin --strip-components 1

      - name: Set FFmpeg version
        working-directory: ${{ github.workspace }}/targets/mvebu/cortexa9
        run: |+
          set -eux
          ./bin/ffmpeg -version
          echo "BUILD_FFMPEG_VERSION=$(./bin/ffmpeg -version | grep -oP '(?<=ffmpeg version ).+(?=https\:)')" >> $GITHUB_ENV

      - name: Generate Release note
        working-directory: imagebuilder
        run: |+
          set -eux

          cat <<EOF> ${{ github.workspace }}-ReleaseNote.txt
          * FFmpeg ${{ env.BUILD_FFMPEG_VERSION }}
          * My repo Commit hash: ${{ github.sha }}

          This encode was built by @naa0yama

          ## sha256sums

          \`\`\`bash

          \`\`\`

          EOF

      # - name: Pre-Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: OpenWrt Custom ${{ env.BUILD_FFMPEG_VERSION }}-${{ env.COMMIT_SHORT_SHA }}
      #     tag_name: ${{ env.BUILD_FFMPEG_VERSION }}-${{ env.COMMIT_SHORT_SHA }}
      #     body_path: ${{ github.workspace }}-ReleaseNote.txt
      #     draft: true
      #     prerelease: true
      #     files: |
